### PR TITLE
Generated with version 2.3.2 using scripts/library-scraper.py

### PR DESCRIPTION
**Pull request by avahidi**
It turns out generating standard profiles is not very easy due to tool incompatibles. And it also takes a lot of time ...

These are unmodified profiles generated by scripts/library-scraper.py but without using scripts/library-profile-generator.sh.

### CODE REVIEW

**Comment by avahidi** [comment]
Updating this profile should really be left out to an automated system.

But that would require support for cumulative updates instead of full rebuilds.

**Review by reddr — CHANGES_REQUESTED** [review]
Thanks for the contribution and sorry for the delay.
Just some minor request, please add a list of library (versions) that do no longer exist, as I added a couple of ad/tracking libs that are not hosted in a remote central repo or older Facebook versions that are similarly not available. I will then try to regenerate profiles for them.

**Comment by reddr** [comment]
@avahidi  You are right, optimally this would be a fully automated task. However, this would require some changes to the scripts (e.g. cumulative updates if the profiling settings did not change). 

As said above, some special handling for library (versions) that are not available at central repos is also necessary (publicly re-distributing these SDKs is legally problematic).
If you have suggestions or want to contribute, you're welcome!

The profile-generator script allows you to generate the profiles with multiple threads with speeds up the process significantly (e.g. one library category per thread). I also thinking about adding support to generate a multi-version profile per library, but I don't have time to do this atm.

**Comment by avahidi** [comment]
> Thanks for the contribution and sorry for the delay.
> Just some minor request, please add a list of library (versions) that do no longer exist, as I added a couple of ad/tracking libs that are not hosted in a remote central repo or older Facebook versions that are similarly not available. I will then try to regenerate profiles for them.

I don't think it is 100% accurate but the only method I can think of is to compare the filenames:

```
find  LibScout-Profiles-new/profiles -name "*.libv" -exec basename {} .libv \;  | sort > new.txt
find  LibScout-Profiles/profiles -name "*.lib" -exec basename {} .lib \;  | sort > old.txt
diff -y --suppress-common-lines old.txt new.txt
```

Would that suffice?

**Comment by reddr** [comment]
Should suffice, since only the file extension changed. Put that file in the top-level dir.

**Review by reddr — APPROVED** [review]

**Pull request merged**
